# Use this Dockerfile if you want to run on NVIDIA_GEFORCE_5090
FROM nvidia/cuda:12.8.0-devel-ubuntu24.04
LABEL maintainer="disi-Unibo-NLP"

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace
ENV APP_PATH=/workspace


ENV TORCH_CUDA_ARCH_LIST="12.0"

# Install dependencies including python3.12-venv
RUN apt-get update -y && \
    apt-get install -y curl \
                       git \
                       bash \
                       nano \
                       python3.12 \
                       python3-pip \
                       python3.12-venv && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# Create and activate virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip
RUN pip install wheel setuptools packaging ninja

RUN pip install wrapt --upgrade --ignore-installed
RUN pip install gdown


COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Install PyTorch with CUDA 12.8 support for RTX 5090
RUN pip install --no-cache-dir \
    torch==2.7.1+cu128 \
    torchvision==0.22.1+cu128 \
    torchaudio==2.7.1+cu128 \
    --index-url https://download.pytorch.org/whl/cu128



# Install flash-attn with RTX 5090 specific compilation flags
RUN VLLM_FLASH_ATTN_VERSION=2 MAX_JOBS=16 FLASH_ATTN_CUDA_ARCHS=128 pip install flash-attn --no-build-isolation


ENV DEBIAN_FRONTEND=dialog